default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: e-commerce.cj3oddyv0bsk.us-west-1.rds.amazonaws.com
      port: 5432
      user: postgres
      password: Welcome!234
      database: Airbyte
      schema: test