
version: 2

models:
    - name: Test
      description: "Test models"
      columns: 
          - name: Test_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: first_name
            description: "User name"
            tests: 
                - not_null
          - name: last_name
            description: "user last name"
            tests:
                - not_null
                
                
